# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-17 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='timelapseParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_images', models.IntegerField()),
                ('length', models.IntegerField()),
                ('interval', models.IntegerField()),
                ('shutter_speed', models.IntegerField()),
                ('direction', models.CharField(max_length=1)),
            ],
        ),
    ]
